### ISSUE TITLE
Remove wind from input file

### ISSUE THREAD

**Issue by ejay** [B00ms/energyGridSimulation#10]
Generate windspeed from weibull distribution.

**Comment by B00ms** [comment]
Values from the input file should be overwritten when doing the MC draws. 
Please double check and close if correct.

**Comment by ejay** [comment]
for the last constraint for wind production based on windspeed we currently use: 
(mcDraw <= V_CUT_IN && mcDraw <= V_CUT_OFF){
but is already met by the following:
if(mcDraw <= V_CUT_IN || mcDraw >= V_CUT_OFF){
and im not sure why this is used, minimum production for wind is not possible because below the cutin. so i removed this.

**Comment by ejay** [comment]
Laura also has the following to set the production to Prated. and i have added it now to the program
          VRATED <= mcDraw && mcDraw <= V_CUT_OFF
elseif TurbGen(i,3)<=MCWind(i,h) && MCWind(i,h)<=TurbGen(i,2)    

fixed in ab8fea1be9de0d73cf9862609822fcf6f665543a
