### ISSUE TITLE
Step 2: Real simulation using scheduled production

### ISSUE THREAD

**Issue by ejay** [B00ms/energyGridSimulation#27]
deltaP  = Real load - Real total production
- [x] **deltaP ~ 0** (Ok)
- [x] **deltaP > 0** 
- [x] increase production (offers)
- [x] storage discharge
- [x] left over load = EENS
- [x] **deltaP < 0**
- [x] decrease production (offers)
- [x] switch off generators for 1h (cheap, oil threshold 60 minimum)
- [x] charge storage

**Comment by B00ms** [comment]
This done expect for the EENS part right?
