### ISSUE TITLE
Get production/ load clear

### ISSUE THREAD

**Issue by ejay** [B00ms/energyGridSimulation#51]
Currently 
load = load + discharge from storage node - renewable production 
production = production conv gen 

Should be 
load = load + discharge from storage node
production = production conv gen + production renewable gen

**Comment by B00ms** [comment]
Laura said renewable production should be subtracted from the load.
I think this is mostly semantic issue though.

**Comment by ejay** [comment]
I thought she just said yesterday that it would be more clear if load would be load, and production would be production, so conventionalProduction+renewableProduction = currentRealProduction

**Comment by B00ms** [comment]
I think real production is the production you get after handling the offers.
Real load is then the load from consumers after Monte Carlo stuff.

Effective load is then real load + charge storage - renewable prod.
This is also why we had to make that value absolute.
