### ISSUE TITLE
in config dailyMaxLoadDemand is semi hardcoded

### ISSUE THREAD

**Issue by ejay** [B00ms/energyGridSimulation#52]
why is dailyMaxLoadDemand  set to 9716?
This seems to be from the thesis and is for the summer period, probably this should be removed from the config or the config should have need a seasonal config, e.g. in one of the input files not the config file per se

table 7.6 from her thesis
Season Maximum demand MW
Winter 9866
Spring 8652
Summer **9716**
Autumn 8559

**Comment by ejay** [comment]
@B00ms

**Comment by B00ms** [comment]
I think the simulation runs separately for each seasons.
So if you want to run a simulation for winter or spring you'd have to changed the value in the config and process those outputs separately yourself.

**Comment by ejay** [comment]
So one run is only for one season and not run for multiple seasons, thats fine by me
