### ISSUE TITLE
Implement price offering

### ISSUE THREAD

**Issue by ejay** [B00ms/energyGridSimulation#6]

**Comment by ejay** [comment]
the current issue with checkGridEquilibrium is that the load is always higher than the production, this is currently because conventionalProduction is always 0.0

**Comment by B00ms** [comment]
No it's not, in most cases the load is higher but on some rare occasions it is lower. 
You could double check the implementation of the load calculation.

In addition it might be better to check if a generator is up or down using a boolean and only return production when the boolean is true.

**Comment by ejay** [comment]
That is what i meant, load is mostly higher than the current production, but i think it is because of the following: 

<img width="345" alt="screenshot 2016-05-04 12 55 18" src="https://cloud.githubusercontent.com/assets/202154/15012257/88eaf6f4-11f7-11e6-9c59-487e0dcfb161.png">
_debug output from checkGridEquilibrium() after calculating total demand_

The problem is the total production for the conventional generators is 0.0.

At the present state the production is never been set for the conventional generators, working on a fix now.
