### ISSUE TITLE
Error in setGridState()?

### ISSUE THREAD

**Issue by B00ms** [B00ms/energyGridSimulation#7]
```
On line 131 we define convGeneratorProb = 0 
On line 150 we do if(mcDraw < convgeneratorProb) {
generator failure
}

```

In between convGeneratorProb  is not changed so the probability that a generator fails is always 0?
Shouldn't we determine what value convGeneratorProb should have?

**Comment by ejay** [comment]
changed according to laura's matlab where she uses 0.5 for initial states of the plants 

 StPl0=rand(NT,1); %initial state of all NT plants
    for i=1:NT
        if StPl0(i,1)<0.5
            StPl0(i,1)=0;
        else
            StPl0(i,1)=1;
        end
    end
