### ISSUE TITLE
Conventional generator

### ISSUE THREAD

**Issue by B00ms** [B00ms/energyGridSimulation#9]
I noticed that conventional generators are almost always out of order when running setGridState(). 
I'm really doubtful that the output that we're generating now is what we want.
You can check output of generators by uncommenting the last line in model.mod.

**Comment by ejay** [comment]
what do you mean with out of order? your applying monte carlo to the monte carlo input so offcourse the values are different

**Comment by B00ms** [comment]
So if you look at the output for the conventional generators (TG) you"ll see that if we use MC draws none of them will produce anything. I ran the MC draws with  convGeneratorProb = 0.1. Just seems to me that the amount of TGs not producing anything is way too high and that renewable generators are producing unrealistically high.

without MC draws: https://jpst.it/HUDv
with MC draws: https://jpst.it/HUDL

TG = conventional generators, ID of generator, power produced.
TG,0, -0.0000

**Comment by ejay** [comment]
Thats because mcDraw currently outputs -0.04 - 0.04 which is always below the 0.1 probability, ill see if i can fix this. Which is because it currently randomly picks a number around 0 with sigma 0.05.

Cheers

**Comment by ejay** [comment]
fixed it currently by using Math.random(), still have to verify if that is right. fac0daf746258611279b68e33248afd51789c1b7

**Comment by B00ms** [comment]
Changed your fix to use the montecarlo helper. also set the failure probability back to 0.5
